highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Swostik Shrestha's Resume
name: Swostik Shrestha
email: slokk03@gmail.com
email_full: mailto:slokk03@gmail.com
website: https://swostik.github.io/
website_full: 
github: Swostik
twitter: slokks
tel: +358 443601655
tel_full: tel:++358443601655
google_maps: 'https://www.google.fi/maps/place/Turku,+20380+Turku/@60.4758626,22.306656,17z/data=!3m1!4b1!4m5!3m4!1s0x468c769bb197a1b9:0x14feaf073bd1115f!8m2!3d60.475864!4d22.3088474'
address:
  street: Emmauksenkatu 7B
  postcode: 20380
  city: Turku
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
